---
- name: Create ssh config
  template:
    src: ssh_config.j2
    dest: "{{ ssh_dir }}/ssh_config"

- name: Create inventory file for AWS hosts
  vars:
    ssh_private_key: "{% raw %}{{ inventory_dir }}{% endraw %}/{{ ssh_dir_name }}/key"
    known_hosts_file: "{% raw %}{{ inventory_dir }}{% endraw %}/{{ ssh_dir_name }}/known_hosts"
  template:
    src: hosts.j2
    dest: "{{ aws_inventory_file }}"

- name: Add hosts keys to known_hosts file
  include_tasks: "{{ role_path }}/tasks/set_known_hosts.yml"
  vars:
    known_hosts_file: "{{ aws_inventory_dir }}/{{ ssh_dir_name }}/known_hosts"
    hosts: "{{ ec2.results|map(attribute='public_ip')|list }}"
  when: instance_count > 0
